# Default configuration file for the JSON API extension.

# List the contenttypes that are to be served through the JSON extension.
# Only contenttypes listed here will be served; for any other contenttype,
# the API will return errors.
contenttypes:
    jobs:
        # The `list-fields` setting allows you to override the fields that
        # appear in listings. You can add fields as well as taxonomies.
        # list-fields: [ title, slug, teaser, image, tags, categories ]
        # The `item-fields` setting allows you to override the fields that
        # appear in singular item request. Leave empty to show all fields.
        # item-fields: [ title, slug, teaser, image, teaser, body, tags, categories ]
        # The `allowed-fields` setting allows you to set what fields can be
        # shown when using the `fields[entries]` query parameter.
        allowed-fields: [ company, slug, area, position, body, duration ]
        # The `where-clause` setting is useful, if you want to add additional
        # filters by default. These can be overridden using the `filter[entries]`
        # query parameter.
        where-clause:
            status: 'published'
        # The `order` clause allows you to set the default order by when querying results
        order: -datepublish
    pages:
        # To use the defaults for a contenttype, just leave its entry empty.
        # This will include all user-defined fields and taxonomies in the
        # listing, but not any of the fields Bolt adds to all content types,
        # such as 'datecreated'.

thumbnail:
    width: 400
    height: 300

headers:
    'Access-Control-Allow-Origin': '*'
    'Content-Type': 'application/vnd.api+json'

replacements:
    'src="//': 'src="http://'
    'href="//': 'href="http://'

# The base url where the API is accessible.
base: '/json'

# If you set this to 'true', all datetime fields will be formatted as ISO 8601 dates
date-iso-8601: true

# See http://php.net/manual/en/json.constants.php
# Some recommended options:
# -   0 for no options (recommended for production)
# - 128 for pretty print (recommended for testing/development)
jsonoptions: 0

# Set this to true to disable frontend completely and display an empty page
disablefrontend: false

# Adds a `ownerdisplayname` which has the record's ownerid's display name
enabledisplaynames: false
